version: '3.7'

services:

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    volumes:
      - ./client/:/app
    ports:
      - 4200:4200
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SERVER_URL=http://127.0.0.1:8080
    stdin_open: true

  api:
    container_name: api
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    restart: on-failure
    ports:
      - 8080:80
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:${DATABASE_PASSWORD:-root}@database:3306/fsapi?serverVersion=8&charset=utf8mb4

  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fsapi
    volumes:
      - ./mysql:/var/lib/mysql:rw
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 20s
      retries: 10
