<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOF8xh41\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOF8xh41/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOF8xh41.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOF8xh41\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOF8xh41\App_KernelDevDebugContainer([
    'container.build_hash' => 'OF8xh41',
    'container.build_id' => '796eec27',
    'container.build_time' => 1696709663,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOF8xh41');
